### ISSUE TITLE
Create ESLint configuration files

### ISSUE THREAD

**Issue by cboulanger** [qooxdoo/qx-dev-manual#1]
This involves:

- [ ] translating the current qooxdoo coding style into [ESLint Syntax](http://eslint.org/docs/user-guide/configuring)
- [ ] Loosening the rules where no consensus can be found (avoiding religious wars)
- [ ] taking care that these configurations files are pluggable into the new qxcompiler toolchain (@johnspackman)

**Comment by hkollmann** [comment]
For a first discussion we have this: https://github.com/qooxdoo/eslint-config-qx

**Comment by cboulanger** [comment]
Already implemented
